# Generated by Django 5.2.1 on 2025-05-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
