# Generated by Django 5.2.1 on 2025-05-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworld', '0002_rename_author_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
